FROM node:latest

RUN mkdir /app
RUN npm install react-scripts@3.0.1 -g
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json ./package-lock.json /app/
RUN npm install --production
EXPOSE $PORT
COPY . /app
RUN npx serve -s
