FROM node:latest

RUN mkdir /app
RUN npm install react-scripts@3.0.1 -g
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/package.json
RUN npm install --force
EXPOSE 80
COPY . /app

RUN npx serve -s build

