version: "3"

services:
  frontend:
    container_name: iconic-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    image: bongdev/iconic-frontend

  backend:
    container_name: iconic-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "9080:9080"
    image: bongdev/iconic-backend


#    volumes:
#    - "./tmp"
#    ports:
#    - "8080:8080"
#    entrypoint: ["java", "-jar", "demo.jar"]