version: "2"

services:
  iconic-jenkins:
    image: custom-jenkins
    user: root
    volumes:
      - ~/jenkins:/var/jenkins_home
      - ~/.aws:/root/.aws
    ports:
      - "8081:8080"

  iconic-mariaDB:
    image: mariadb
    user: root
    environment:
      MYSQL_ROOT_PASSWORD : '1234'
    ports:
      - "4406:3306"


#    volumes:
#    - "./tmp"
#    ports:
#    - "8080:8080"
#    entrypoint: ["java", "-jar", "demo.jar"]